name: Deploy Render via Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Verificar tag detectada
        run: echo "Deploy iniciado para a tag ${GITHUB_REF_NAME}"

      - name: Trigger Deploy Render
        run: |
          curl "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}